#!/usr/bin/env python3
"""Codabench scoring program for RealPDE Track 2 LTTTA. Same formulas as Track 1: error scores, sqrt-time, frozen sigma, final subscores only. mean_t_neural_s is measured by the evaluation loop and read from predictions.npz."""

from __future__ import annotations

import html
import json
import math
import sys
from pathlib import Path
from typing import Any

import numpy as np


DEFAULT_IN_STEP = 20
T_NUMERICAL_SEC = 0.72896
# Protocol constant, frozen for the whole season (proposal: "global standard deviation of
# the target variable (precomputed for each dataset)"). Computed from the official
# train_real GaussianNormalizer statistics as std_targets[:2].mean()
# = (0.09681041 + 0.01596364) / 2 — u and v channel stds; matches the reference
# eval pipeline (data_normalizer.py stats tuple (mean_inputs, mean_targets, std_inputs,
# std_targets) + sigma = std_targets[:c].mean(), c=2).
# Source file: mean_std_real.pt, 1920 bytes,
#   sha256 = bae5235f73431ac7d76e6bdcea480b8ca9fda0ac01e57ab26af66bad20dc3b40
# A per-eval-set np.std(t) would drift across phases and pool the u/v channel means
# into the variance; this constant keeps SPS one fixed yardstick.
SIGMA_GLOBAL = 0.0563870259


def find_file(root: Path, name: str) -> Path:
    direct = root / name
    if direct.exists():
        return direct
    matches = sorted(root.rglob(name))
    if not matches:
        raise FileNotFoundError(f"Could not find {name} under {root}")
    return matches[0]


def load_predictions(input_dir: Path) -> dict[str, Any]:
    path = find_file(input_dir, "predictions.npz")
    # Load predictions.npz as untrusted input: allow_pickle=False prevents code
    # execution via a malicious object array.
    with np.load(path, allow_pickle=False) as data:
        result = {k: data[k] for k in data.files}
    if "prediction" not in result:
        raise KeyError("predictions.npz must contain key 'prediction'.")
    result["prediction"] = np.asarray(result["prediction"], dtype=np.float32)
    if "lower" in result:
        result["lower"] = np.asarray(result["lower"], dtype=np.float32)
    if "upper" in result:
        result["upper"] = np.asarray(result["upper"], dtype=np.float32)
    return result


def load_targets_from_npz(reference_dir: Path) -> tuple[np.ndarray, np.ndarray | None]:
    # The reference is exactly reference_dir/targets.npz with keys 'target' and
    # 'sample_id', pre-generated by the official CompetitionAirfoil + TTTDataset
    # loader. The reference horizon is fixed and independent of the prediction.
    path = reference_dir / "targets.npz"
    if not path.exists():
        raise FileNotFoundError(f"Expected fixed reference at {path}")
    # Load without pickle (allow_pickle=False).
    with np.load(path, allow_pickle=False) as data:
        if "target" not in data:
            raise KeyError(f"{path} must contain key 'target'.")
        target = np.asarray(data["target"], dtype=np.float32)
        sample_id = np.asarray(data["sample_id"]) if "sample_id" in data.files else None
    return target, sample_id


def load_targets(reference_dir: Path) -> tuple[np.ndarray, np.ndarray | None]:
    # The reference is a fixed, pre-generated targets.npz (target + sample_id)
    # built by the official CompetitionAirfoil + TTTDataset loader.
    return load_targets_from_npz(reference_dir)


def resolve_reference_dir(input_dir: Path) -> Path:
    # Codabench mounts the reference under <input>/ref; local runs pass an explicit
    # directory as argv[4]. Probe for the fixed targets.npz across the known mount points.
    candidates = [input_dir / "ref"]
    if len(sys.argv) > 4:
        candidates.append(Path(sys.argv[4]))
    candidates += [Path("/app/input/ref"), Path("/app/reference_data")]
    for cand in candidates:
        if (cand / "targets.npz").exists():
            return cand
    return candidates[0]


def measured_channels(target: np.ndarray) -> int:
    channels = target.shape[-1]
    active = []
    for idx in range(channels):
        active.append(not np.allclose(target[..., idx], 0.0))
    count = int(sum(active))
    return max(1, count)


def rel_l2_per_sample(pred: np.ndarray, target: np.ndarray, c: int) -> np.ndarray:
    p = pred[..., :c].reshape(pred.shape[0], -1)
    t = target[..., :c].reshape(target.shape[0], -1)
    denom = np.linalg.norm(t, axis=1).clip(min=1e-8)
    return np.linalg.norm(p - t, axis=1) / denom


def kinetic_energy(x: np.ndarray) -> np.ndarray:
    u = x[..., 0]
    v = x[..., 1]
    u_prime = np.mean((u - np.mean(u, axis=1, keepdims=True)) ** 2, axis=1)
    v_prime = np.mean((v - np.mean(v, axis=1, keepdims=True)) ** 2, axis=1)
    return 0.5 * (u_prime + v_prime)


def tke_rel_l2_per_sample(pred: np.ndarray, target: np.ndarray, c: int) -> np.ndarray:
    if c < 2:
        return np.zeros((pred.shape[0],), dtype=np.float32)
    pred_ke = kinetic_energy(pred[..., :c])
    target_ke = kinetic_energy(target[..., :c])
    p = pred_ke.reshape(pred.shape[0], -1)
    t = target_ke.reshape(target.shape[0], -1)
    denom = np.linalg.norm(t, axis=1).clip(min=1e-8)
    return np.linalg.norm(p - t, axis=1) / denom


def mvpe_rel_l2_per_sample(pred: np.ndarray, target: np.ndarray, sub_s_real: int = 2) -> np.ndarray:
    d = 16
    center_x = 10
    center_y = 32
    n_probe = 9
    N, _, h, w, _ = pred.shape
    probe_center_y = int(center_y / sub_s_real)
    interval_y = min(2, int(h / (n_probe + 1)))
    probe_y = [
        probe_center_y + interval_y * j
        for j in range(-(n_probe - 1) // 2, n_probe - (n_probe - 1) // 2)
    ]
    probe_y = [y for y in probe_y if 0 <= y < h]
    if not probe_y:
        return np.zeros((N,), dtype=np.float32)

    errors = []
    for i in range(4):
        if int((2 * d + center_x) / sub_s_real) < w:
            probe_x = int(((i + 1) * d + center_x) / sub_s_real)
        else:
            probe_x = int((0.5 * (i + 2) * d + center_x) / sub_s_real)
        if not 0 <= probe_x < w:
            continue
        pp = pred[:, :, probe_y, probe_x, :2].mean(axis=1).reshape(N, -1)
        tt = target[:, :, probe_y, probe_x, :2].mean(axis=1).reshape(N, -1)
        denom = np.linalg.norm(tt, axis=1).clip(min=1e-8)
        errors.append(np.linalg.norm(pp - tt, axis=1) / denom)
    if not errors:
        return np.zeros((N,), dtype=np.float32)
    return np.mean(np.stack(errors, axis=0), axis=0)




def mvpe_rel_l2(pred: np.ndarray, target: np.ndarray, sub_s_real: int = 2) -> float:
    return float(np.mean(mvpe_rel_l2_per_sample(pred, target, sub_s_real)))


def score_error(err: float, scale: float = 0.5) -> float:
    if not np.isfinite(err):
        return 0.0
    return float(100.0 / (1.0 + abs(scale) * max(float(err), 0.0)))


def score_time(t_neural: float, r_min: float = 1.0) -> float:
    # sqrt time metric: ST = 1 / (1 + (r / r_min) ** 0.5), r = t_neural / t_numerical;
    # score = 100 * ST. A missing, zero, negative, or non-finite per-step time is not a
    # real measurement (inference always takes positive wall time), so it scores 0.
    if not np.isfinite(t_neural) or t_neural <= 0.0:
        return 0.0
    r = float(t_neural) / T_NUMERICAL_SEC
    st = 1.0 / (1.0 + (r / r_min) ** 0.5)
    return float(100.0 * st)


def aggregate_sps(
    pred: np.ndarray,
    target: np.ndarray,
    c: int,
    lower: np.ndarray | None = None,
    upper: np.ndarray | None = None,
    normalize_factor: float = 0.5,
    weight_dm: float = 0.5,
    weight_tke: float = 0.3,
    weight_mvpe: float = 0.2,
) -> tuple[float, float]:
    p = pred[..., :c]
    t = target[..., :c]
    sigma = SIGMA_GLOBAL
    if lower is None or upper is None:
        interval = 0.1 * np.abs(p)
        lower = p - interval / 2.0
        upper = p + interval / 2.0
    else:
        # Participant-supplied bounds must be per-element (same shape as the measured
        # prediction), finite, and correctly ordered; reject anything else rather than
        # broadcasting a scalar or silently accepting a reversed interval.
        lower = np.asarray(lower, dtype=np.float32)[..., :c]
        upper = np.asarray(upper, dtype=np.float32)[..., :c]
        if lower.shape != p.shape or upper.shape != p.shape:
            raise ValueError(
                f"SPS bounds shape {lower.shape}/{upper.shape} must match prediction {p.shape}"
            )
        if not (np.all(np.isfinite(lower)) and np.all(np.isfinite(upper))):
            raise ValueError("SPS bounds must be finite.")
        if np.any(lower > upper):
            raise ValueError("SPS bounds require lower <= upper for every element.")

    inside = (t >= lower) & (t <= upper)
    nil = (upper - lower) / sigma

    dm = rel_l2_per_sample(pred, target, c)
    tke = tke_rel_l2_per_sample(pred, target, c)
    mvpe = mvpe_rel_l2_per_sample(pred, target)

    dm = dm / (normalize_factor + dm)
    tke = tke / (normalize_factor + tke)
    mvpe = mvpe / (normalize_factor + mvpe)


    def branch(pm: np.ndarray) -> float:
        shaped_pm = pm.reshape((pm.shape[0],) + (1,) * (p.ndim - 1))
        elem = (1.0 - shaped_pm) * np.exp(-nil)
        elem = np.where(inside, elem, 0.0)
        elem = np.where(np.isfinite(shaped_pm), elem, np.nan)
        val = float(np.nanmean(elem))
        return val if np.isfinite(val) else 0.0

    sps_dm = branch(dm)
    sps_tke = branch(tke)
    sps_mvpe = branch(mvpe)
    weighted = weight_dm * sps_dm + weight_tke * sps_tke + weight_mvpe * sps_mvpe
    coverage = float(np.mean(inside))
    return weighted, coverage


def score_sps(value: float) -> float:
    if not np.isfinite(value):
        return 0.0
    # Clamp before exp so an extreme value cannot overflow math.exp.
    x = max(-60.0, min(60.0, float(value)))
    return float(100.0 / (1.0 + math.exp(-x)))


def validate_shapes(pred: np.ndarray, target: np.ndarray) -> None:
    if pred.ndim != 5:
        raise ValueError(f"Prediction must have shape (N,T,H,W,C), got {pred.shape}")
    if target.ndim != 5:
        raise ValueError(f"Target must have shape (N,T,H,W,C), got {target.shape}")
    if pred.shape != target.shape:
        raise ValueError(f"Prediction shape {pred.shape} does not match target shape {target.shape}")


def check_sample_ids(pred_sample_id: Any, target_sample_id: np.ndarray | None) -> None:
    # Order-sensitive alignment between the predictions.npz sample_id and the fixed
    # reference sample_id: a missing / reordered / wrong-length sample_id raises, which
    # degrades to ZERO_SCORES via main()'s guard. This binds every predicted window to a
    # specific (sim_id, time_id) so each prediction is scored against the correct row.
    if target_sample_id is None:
        raise ValueError("Reference targets.npz is missing key 'sample_id'.")
    if pred_sample_id is None:
        raise ValueError("predictions.npz must contain key 'sample_id'.")
    pred_ids = np.asarray(pred_sample_id).astype(str).ravel()
    ref_ids = np.asarray(target_sample_id).astype(str).ravel()
    if pred_ids.shape[0] != ref_ids.shape[0]:
        raise ValueError(
            f"sample_id count {pred_ids.shape[0]} does not match reference {ref_ids.shape[0]}."
        )
    if not np.array_equal(pred_ids, ref_ids):
        n_diff = int(np.count_nonzero(pred_ids != ref_ids))
        raise ValueError(
            f"sample_id sequence does not match reference ({n_diff}/{ref_ids.shape[0]} differ); "
            "predictions must be in the exact trajectory order emitted by the evaluator."
        )


def _fmt(value: Any) -> str:
    return f"{value:.6f}" if isinstance(value, (int, float)) else str(value)


def write_detailed_results(output_dir: Path, scores: dict[str, Any]) -> None:
    # Escape both the key and the formatted value for safe HTML output; html.escape is
    # the identity on ordinary subscore keys and numeric strings. The document variable
    # is named to avoid shadowing the imported html module.
    rows = "\n".join(
        f"<tr><th>{html.escape(key)}</th><td>{html.escape(_fmt(value))}</td></tr>"
        for key, value in scores.items()
    )
    document = f"""<!doctype html>
<html>
<head><meta charset="utf-8"><title>RealPDE LTTTA Results</title></head>
<body>
<h1>RealPDE Track 2 LTTTA Results</h1>
<table>{rows}</table>
</body>
</html>
"""
    (output_dir / "detailed_results.html").write_text(document, encoding="utf-8")


ZERO_SCORES = {
    "rel_l2_score": 0.0, "tke_score": 0.0, "mvpe_score": 0.0,
    "time_score": 0.0, "sps_score": 0.0, "final_score": 0.0,
}


def _write(output_dir: Path, scores: dict) -> None:
    with open(output_dir / "scores.json", "w", encoding="utf-8") as f:
        json.dump(scores, f, indent=2)
    write_detailed_results(output_dir, scores)


def _score_submission(input_dir: Path, reference_dir: Path) -> dict:
    pred_bundle = load_predictions(input_dir)
    pred = np.asarray(pred_bundle["prediction"], dtype=np.float32)
    target, target_sample_id = load_targets(reference_dir)
    validate_shapes(pred, target)
    check_sample_ids(pred_bundle.get("sample_id"), target_sample_id)

    # A valid submission must produce finite predictions everywhere; a non-finite
    # prediction is invalid and scores zero on every subscore.
    if not np.all(np.isfinite(pred)):
        return dict(ZERO_SCORES)

    c = measured_channels(target)
    rel_l2 = float(np.mean(rel_l2_per_sample(pred, target, c)))
    tke = float(np.mean(tke_rel_l2_per_sample(pred, target, c)))
    mvpe = mvpe_rel_l2(pred, target)
    mean_t_neural_s = float(np.asarray(pred_bundle.get("mean_t_neural_s", [0.0])).reshape(-1)[0])
    sps, coverage = aggregate_sps(
        pred,
        target,
        c,
        lower=pred_bundle.get("lower"),
        upper=pred_bundle.get("upper"),
    )

    # Output carries the 0-100 subscores and the composite.
    scores = {
        "rel_l2_score": score_error(rel_l2),
        "tke_score": score_error(tke),
        "mvpe_score": score_error(mvpe),
        "time_score": score_time(mean_t_neural_s),
        "sps_score": score_sps(sps),
    }
    scores["final_score"] = float(
        np.mean(
            [
                scores["rel_l2_score"],
                scores["tke_score"],
                scores["mvpe_score"],
                scores["time_score"],
                scores["sps_score"],
            ]
        )
    )
    return scores


def main() -> None:
    input_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("/app/input")
    output_dir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("/app/output")
    reference_dir = resolve_reference_dir(input_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Any failure parsing/validating the submission bundle yields a controlled
    # zero-score result rather than an uncaught crash. SystemExit is re-raised.
    try:
        scores = _score_submission(input_dir, reference_dir)
    except SystemExit:
        raise
    except Exception as exc:  # noqa: BLE001 - untrusted input, degrade to zero
        scores = dict(ZERO_SCORES)
        scores["error"] = f"{type(exc).__name__}: {exc}"[:200]
    _write(output_dir, scores)


if __name__ == "__main__":
    main()
